### ISSUE TITLE
the transform of raw waveforms and noise waveforms

### ISSUE THREAD

**Issue by bestfzy** [smousavi05/STEAD#11]
Hello, I am a first-year student at Harbin Institute of Technology in China, and my recent study needs to use the stead dataset.
First of all, I am very grateful for your efforts to create such a global seismic data set, which greatly facilitates subsequent researchers.
Then I noticed that you provided a method to convert the original waveform of ground motion into acceleration, velocity, and displacement.
What I need is the acceleration record, but at the same time I also need the noise acceleration record, so I want to ask you, how to convert the noise waveform into the acceleration record? What are the physical properties of the original waveform records of noise?
Thank you very much for answering my confusion！！！

**Comment by smousavi05** [comment]
Hello, @bestfzy

Thanks for your email and interest in using STEAD. You can convert the
noise data into acceleration using the same procedure as the earthquake
data.
Noise in STEAD dataset consists of a variety of noises recorded by seismic
instruments including random noise, ambient noise, man-made noise,
atmospheric noise, etc.
Hope this helps.

**Comment by bestfzy** [comment]
Thanks a lot for your answer, I'm trying the same procedure to convert noise data to acceleration data.
Good luck with your work!

**Comment by bestfzy** [comment]
Hello, I would like to ask, the method you provided to convert the raw data into acceleration and displacement data, whether the obtained acceleration and displacement are filtered, similar to Butterworth filter, can be directly applied to engineering practice.
Since my application requires already processed ground motion acceleration and displacement data, I would like to ask you.
Thank you very much for answering my confusion！！！

**Comment by smousavi05** [comment]
The data has been already processed including band-pass filtering of 1-45
Hz. So when you convert data to acceleration only amplitude values changing
and obtained data is already pre-processed
