### ISSUE TITLE
STEAD Data filtering

### ISSUE THREAD

**Issue by Steven-meta** [smousavi05/STEAD#12]
Thank you for your efforts to build the STEAD dataset. I also tried to use it for my analysis.

Regarding the STEAD dataset, I would like to ask whether this data is filtered or not?  From your following papers titled “A machine‐learning approach for earthquake magnitude estimation” and “Earthquake transformer—an attentive deep-learning model for simultaneous earthquake detection and phase picking”, the STEAD data is filtered by a band-pass filter using different frequency ranges of 1-40Hz and 1 - 45Hz. I would like to know why they use different frequency ranges?

Thanks

**Comment by smousavi05** [comment]
Hi, No, the dataset has been filtered between 1-45hz as you can see in the
STEAD paper.

There should be a mistake or typo in other papers otherwise the bandpass
filtering is the same.

Mostafa
