### ISSUE TITLE
Instrument Response

### ISSUE THREAD

**Issue by gchrispin** [smousavi05/STEAD#13]
Hi!

This dataset is great! Thanks for putting it together.

I ran into a problem of not finding the instrument response for a lot of the events. I am only trying to find them from the IRIS website. Is there another place other than IRIS where instrument responses can be found for this dataset?

Thanks!

**Comment by smousavi05** [comment]
@gchrispin it should be because of the stations that you are interested in. So recommend checking directly with the network running those stations. Sometimes you can find the instrument responses directly on the local seismic network website.
