### ISSUE TITLE
I wondered why each waveform has a 60 seconds ground motion in STEAD. Is there any scientific evidence behind it?

### ISSUE THREAD

**Issue by andrewbauras** [smousavi05/STEAD#14]
I wondered why each waveform has a 1-minute long ground motion in STEAD. Is there any scientific evidence behind it?

**Comment by smousavi05** [comment]
The window lenght is selected based on the distance and msgnitude range of
earthquakes in a way it cover the entire waveform.

**Comment by andrewbauras** [comment]
Thank you for the answer and your prompt response.
