### ISSUE TITLE
Acceleration Data Acquisition Method

### ISSUE THREAD

**Issue by cyling250** [smousavi05/STEAD#21]
Thank you very much for your contribution to building the STEAD dataset, which I also intend to use.

For my work, we are more concerned with the acceleration waveform of ground motion, and you also give the method of obtaining the acceleration waveform in the article.

```
client = Client("IRIS")
inventory = client.get_stations(network=quake_wave_set.attrs['network_code'],
    station=quake_wave_set.attrs['receiver_code'],
    starttime=UTCDateTime(quake_wave_set.attrs['trace_start_time']),
    endtime=UTCDateTime(quake_wave_set.attrs['trace_start_time']) + 60,
    loc="*",
    channel="*",
    level="response")
st = make_stream(quake_wave_set)
st = st.remove_response(inventory=inventory, output="ACC", plot=False)
```

When I use this method to acquire acceleration waveforms, I will get data from IRIS over the network, which is simple and feasible for a small number of seismic waves. But when I request more, IRIS rejects my request. I also realized that for millions of orders of data, it is almost impossible in this way.

I would like to ask if you have ground motion acceleration waveform data, or could you please give me another way to get ground motion acceleration waveform for the entire data set?

Thank you so much!

**Comment by smousavi05** [comment]
Hello,

I don't have acceleration data. The reason for this issue is that IRIS
server has a cap for number of requests per person per time. If you simply
add a waiting period (like 10 section) between each time you runn the below
script, you won't get that error message.

Regards,
Mostafa

**Comment by cyling250** [comment]
Thank you very much, this is helpful.
