### ISSUE TITLE
Downloading only the csv files

### ISSUE THREAD

**Issue by am-thomas** [smousavi05/STEAD#22]
Hi,
Is it possible to only downloaded the metadata csv files for STEAD? Ideally, I would love the retrieve csvs for each chunk of data. But, the csv for the merged data would be great too. Thank you.

**Comment by smousavi05** [comment]
Hi,

Please find the metadata file for the entire dataset attached.

 metadata_05_15_20.csv
<https://drive.google.com/file/d/1LUGGpwRwFX6cVdE5yJsoPqWxyXcVul7g/view?usp=drive_web>

**Comment by am-thomas** [comment]
Thank you very much. This saved me a lot of time and storage.
