### ISSUE TITLE
Data-download

### ISSUE THREAD

**Issue by crimeacs** [smousavi05/STEAD#4]
Hello, there is currently no way to download data automatically. Google is throwing following error when accessed from the terminal: 

`Access denied with the following error:
 	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator.
You may still be able to access the file from the browser`

MEGA is also not really suitable for wget and curl

**Comment by smousavi05** [comment]
Hi, unfortunately, that problem still exists for automatic downloading. For now, I could only recommend manually downloading the parts you need on your local machine and then moving it into your remote machine/cluster. We are working on it and will post the new options once we got them.

**Comment by malcolmw** [comment]
@crimeacs @smousavi05 

I successfully downloaded the data from the command line using this [megadown](https://github.com/tonikelope/megadown) tool. Note that you will need to use the trick from [this issue](https://github.com/tonikelope/megabasterd/issues/215#issue-593295064). 

For example, after installing _megadown_ and its dependencies, execute

`sh$> megadown 'https://mega.nz/#!6YoXjThT!chwK8lG8pAheUVdFlojEMdSiOuk0n186JjFFnGIhFdo'`

to download _chunk1.hdf5_. 

Hope that helps!
