### ISSUE TITLE
Trouble in citing STEAD dataset for AGU submission

### ISSUE THREAD

**Issue by MrXiaoXiao** [smousavi05/STEAD#6]
Hello, thanks for your great data.
I met weird trouble when citing the STEAD dataset in my work for AGU submission.
I stated in 'Data and materials availability': STanford EArthquake Dataset (STEAD) used for training is available at https://github.com/smousavi05/STEAD. 
However, I got the following submission error:

* Github is not an archival repository; please instead deposit your data/code in a suitable repository and update your data availability statement. To facilitate this, Github offers a one-click link to make your code and data citable by depositing it in Zenodo or figshare. Information on preserving your data or code in Zenodo and making it citable can be found here: https://guides.github.com/activities/citable-code/

So, can you generate a DOI for STEAD dataset so that I can cite it for AGU submission?

Sorry for the trouble. Thanks again for your work : )

**Comment by smousavi05** [comment]
Hi, you should have used the reference to our paper or its doi:

Mousavi, S. M., Sheng, Y., Zhu, W., Beroza G.C., (2019). STanford EArthquake Dataset (STEAD): A Global Data Set of Seismic Signals for AI, IEEE Access, doi:10.1109/ACCESS.2019.2947848

**Comment by MrXiaoXiao** [comment]
I have already used the reference to your paper. That's why I felt weird about the error. I will try the paper's doi in acknowledgements. Thank you.
