### ISSUE TITLE
Site-characterization parameter

### ISSUE THREAD

**Issue by xzk8559** [smousavi05/STEAD#9]
Is it possible to add some site-characterization parameters？
Such as the site classification according to codes or guidelines, or the average shear-wave velocity.
If so, this work will have much greater application scenarios.

**Comment by xzk8559** [comment]
Also, I'm curious about why the duration is less than one minute? Are the records cropped?
Because other databases (like Kik-net) contain many longer records.

**Comment by smousavi05** [comment]
@xzk8559 this is a global dataset the amount of data for site characterization and their accuracy differ from one region to another. You can use the estimates of global Vs30 from USGS website for the station locations as a rough estimation of the site term. This dataset mainly include the earthquake waveforms. This is why it was cut to 1 min window around single earthquake waveform. This is not an archive of continuous data like Kik-net

**Comment by xzk8559** [comment]
I have found the released Vs30 map on USGS website, thanks!
